### ISSUE TITLE
Add default type of activation function parameter

### ISSUE THREAD

**Issue by chenIshi** [chenIshi/FPNN#2]
In include/activate_temp.h, according different config define, activation function will have different numerical type

However, if not properly config (although running "./config" itself should prevent such cases),
it will probably result in no macro definition in such keyword

Please add default define for such keyword

**Comment by jesus255221** [comment]
The header has already fix and change its type to .c file.
Therefore, it is now located in the src folder. 
Additionally, the bug which comes from the macro has already been fixed.
